jwtSecret: "S3cr3t!"
registration:
  password:
    minLength: 8
    maxLength: 20
    minLowercase: 2
    minNumbers: 2
    minSymbols: 2
    minUppercase: 2
  handle:
    minLength: 2
    maxLength: 32
  displayName:
    minLength: 2
    maxLength: 32

  minAge: 13
  maxAge: 50
