import { ApiException } from "./exceptions/api.exeption";

// ACCOUNT_COMPROMISED_RESET_PASSWORD Please reset your password to log in.

export const DISCORD_API_ERRORS = {
  GENERAL_ERROR: new ApiException("General error (such as a malformed request body, amongst other things)", 0),
  UNKNOWN_ACCOUNT: new ApiException("Unknown account", 10001),
  UNKNOWN_APPLICATION: new ApiException("Unknown application", 10002),
  UNKNOWN_CHANNEL: new ApiException("Unknown channel", 10003),
  UNKNOWN_GUILD: new ApiException("Unknown guild", 10004),
  UNKNOWN_INTEGRATION: new ApiException("Unknown integration", 10005),
  UNKNOWN_INVITE: new ApiException("Unknown invite", 10006),
  UNKNOWN_MEMBER: new ApiException("Unknown member", 10007),
  UNKNOWN_MESSAGE: new ApiException("Unknown message", 10008),
  UNKNOWN_OVERWRITE: new ApiException("Unknown permission overwrite", 10009),
  UNKNOWN_PROVIDER: new ApiException("Unknown provider", 10010),
  UNKNOWN_ROLE: new ApiException("Unknown role", 10011),
  UNKNOWN_TOKEN: new ApiException("Unknown token", 10012),
  UNKNOWN_USER: new ApiException("Unknown user", 10013),
  UNKNOWN_EMOJI: new ApiException("Unknown emoji", 10014),
  UNKNOWN_WEBHOOK: new ApiException("Unknown webhook", 10015),
  UNKNOWN_WEBHOOK_SERVICE: new ApiException("Unknown webhook service", 10016),
  UNKNOWN_SESSION: new ApiException("Unknown session", 10020),
  UNKNOWN_BAN: new ApiException("Unknown ban", 10026),
  UNKNOWN_SKU: new ApiException("Unknown SKU", 10027),
  UNKNOWN_STORE_LISTING: new ApiException("Unknown Store Listing", 10028),
  UNKNOWN_ENTITLEMENT: new ApiException("Unknown entitlement", 10029),
  UNKNOWN_BUILD: new ApiException("Unknown build", 10030),
  UNKNOWN_LOBBY: new ApiException("Unknown lobby", 10031),
  UNKNOWN_BRANCH: new ApiException("Unknown branch", 10032),
  UNKNOWN_STORE_DIRECTORY_LAYOUT: new ApiException("Unknown store directory layout", 10033),
  UNKNOWN_REDISTRIBUTABLE: new ApiException("Unknown redistributable", 10036),
  UNKNOWN_GIFT_CODE: new ApiException("Unknown gift code", 10038),
  UNKNOWN_STREAM: new ApiException("Unknown stream", 10049),
  UNKNOWN_PREMIUM_SERVER_SUBSCRIBE_COOLDOWN: new ApiException("Unknown premium server subscribe cooldown", 10050),
  UNKNOWN_GUILD_TEMPLATE: new ApiException("Unknown guild template", 10057),
  UNKNOWN_DISCOVERABLE_SERVER_CATEGORY: new ApiException("Unknown discoverable server category", 10059),
  UNKNOWN_STICKER: new ApiException("Unknown sticker", 10060),
  UNKNOWN_INTERACTION: new ApiException("Unknown interaction", 10062),
  UNKNOWN_APPLICATION_COMMAND: new ApiException("Unknown application command", 10063),
  UNKNOWN_VOICE_STATE: new ApiException("Unknown voice state", 10065),
  UNKNOWN_APPLICATION_COMMAND_PERMISSIONS: new ApiException("Unknown application command permissions", 10066),
  UNKNOWN_STAGE_INSTANCE: new ApiException("Unknown Stage Instance", 10067),
  UNKNOWN_GUILD_MEMBER_VERIFICATION_FORM: new ApiException("Unknown Guild Member Verification Form", 10068),
  UNKNOWN_GUILD_WELCOME_SCREEN: new ApiException("Unknown Guild Welcome Screen", 10069),
  UNKNOWN_GUILD_SCHEDULED_EVENT: new ApiException("Unknown Guild Scheduled Event", 10070),
  UNKNOWN_GUILD_SCHEDULED_EVENT_USER: new ApiException("Unknown Guild Scheduled Event User", 10071),
  UNKNOWN_TAG: new ApiException("Unknown Tag", 10087),
  BOT_PROHIBITED_ENDPOINT: new ApiException("Bots cannot use this endpoint", 20001),
  BOT_ONLY_ENDPOINT: new ApiException("Only bots can use this endpoint", 20002),
  EXPLICIT_CONTENT_CANNOT_BE_SENT_TO_RECIPIENT: new ApiException("Explicit content cannot be sent to the desired recipient(s)", 20009),
  ACTION_NOT_AUTHORIZED_ON_APPLICATION: new ApiException("You are not authorized to perform this action on this application", 20012),
  SLOWMODE_RATE_LIMIT: new ApiException("This action cannot be performed due to slowmode rate limit", 20016),
  ONLY_OWNER: new ApiException("Only the owner of this account can perform this action", 20018),
  ANNOUNCEMENT_RATE_LIMITS: new ApiException("This message cannot be edited due to announcement rate limits", 20022),
  UNDER_MINIMUM_AGE: new ApiException("Under minimum age", 20024),
  CHANNEL_WRITE_RATELIMIT: new ApiException("The channel you are writing has hit the write rate limit", 20028),
  GUILD_WRITE_RATELIMIT: new ApiException("The write action you are performing on the server has hit the write rate limit", 20029),
  WORDS_NOT_ALLOWED: new ApiException("Your Stage topic, server name, server description, or channel names contain words that are not allowed", 20031),
  GUILD_PREMIUM_LEVEL_TOO_LOW: new ApiException("Guild premium subscription level too low", 20035),
  MAXIMUM_GUILDS_REACHED: new ApiException("Maximum number of guilds reached ({})", 30001, undefined, ["100"]),
  MAXIMUM_FRIENDS_REACHED: new ApiException("Maximum number of friends reached ({})", 30002, undefined, ["1000"]),
  MAXIMUM_PINS_REACHED: new ApiException("Maximum number of pins reached for the channel ({})", 30003, undefined, ["50"]),
  MAXIMUM_RECIPIENTS_REACHED: new ApiException("Maximum number of recipients reached ({})", 30004, undefined, ["10"]),
  MAXIMUM_ROLES_REACHED: new ApiException("Maximum number of guild roles reached ({})", 30005, undefined, ["250"]),
  MAXIMUM_WEBHOOKS_REACHED: new ApiException("Maximum number of webhooks reached ({})", 30007, undefined, ["15"]),
  MAXIMUM_EMOJIS_REACHED: new ApiException("Maximum number of emojis reached", 30008),
  MAXIMUM_REACTIONS_REACHED: new ApiException("Maximum number of reactions reached ({})", 30010, undefined, ["20"]),
  MAXIMUM_GROUP_DMS_REACHED: new ApiException("Maximum number of group DMs reached ({})", 30011, undefined, ["10"]),
  MAXIMUM_CHANNELS_REACHED: new ApiException("Maximum number of guild channels reached ({})", 30013, undefined, ["500"]),
  MAXIMUM_ATTACHMENTS_REACHED: new ApiException("Maximum number of attachments in a message reached ({})", 30015, undefined, ["10"]),
  MAXIMUM_INVITES_REACHED: new ApiException("Maximum number of invites reached ({})", 30016, undefined, ["1000"]),
  MAXIMUM_ANIMATED_EMOJIS_REACHED: new ApiException("Maximum number of animated emojis reached", 30018),
  MAXIMUM_SERVER_MEMBERS_REACHED: new ApiException("Maximum number of server members reached", 30019),
  MAXIMUM_SERVER_CATEGORIES_REACHED: new ApiException("Maximum number of server categories has been reached ({})", 30030, undefined, ["5"]),
  GUILD_TEMPLATE_EXISTS: new ApiException("Guild already has a template", 30031),
  MAXIMUM_APPLICATION_COMMANDS_REACHED: new ApiException("Maximum number of application commands reached", 30032),
  MAXIMUM_THREAD_PARTICIPANTS_REACHED: new ApiException("Maximum number of thread participants has been reached ({})", 30033, undefined, ["1000"]),
  MAXIMUM_DAILY_APPLICATION_COMMAND_CREATES_REACHED: new ApiException("Maximum number of daily application command creates has been reached ({})", 30034, undefined, ["200"]),
  MAXIMUM_NON_GUILD_MEMBER_BANS_REACHED: new ApiException("Maximum number of bans for non-guild members have been exceeded", 30035),
  MAXIMUM_BANS_FETCHES_REACHED: new ApiException("Maximum number of bans fetches has been reached", 30037),
  MAXIMUM_UNCOMPLETED_GUILD_SCHEDULED_EVENTS_REACHED: new ApiException("Maximum number of uncompleted guild scheduled events reached ({})", 30038, undefined, ["100"]),
  MAXIMUM_STICKERS: new ApiException("Maximum number of stickers reached", 30039),
  MAXIMUM_PRUNE_REQUESTS: new ApiException("Maximum number of prune requests has been reached. Try again later", 30040),
  MAXIMUM_GUILD_WIDGET_SETTINGS_UPDATES_REACHED: new ApiException("Maximum number of guild widget settings updates has been reached. Try again later", 30042),
  MAXIMUM_OLD_MESSAGE_EDITS_REACHED: new ApiException("Maximum number of edits to messages older than 1 hour reached. Try again later", 30046),
  MAXIMUM_PINNED_FORUM_THREADS_REACHED: new ApiException("Maximum number of pinned threads in a forum channel has been reached", 30047),
  MAXIMUM_FORUM_TAGS_REACHED: new ApiException("Maximum number of tags in a forum channel has been reached", 30048),
  BITRATE_TOO_HIGH: new ApiException("Bitrate is too high for channel of this type", 30052),
  MAXIMUM_PREMIUM_EMOJIS_REACHED: new ApiException("Maximum number of premium emojis reached ({})", 30056, undefined, ["25"]),
  MAXIMUM_WEBHOOKS_PER_GUILD_REACHED: new ApiException("Maximum number of webhooks per guild reached ({})", 30058, undefined, ["1000"]),
  MAXIMUM_CHANNEL_PERMISSION_OVERWRITES_REACHED: new ApiException("Maximum number of channel permission overwrites reached ({})", 30060, undefined, ["1000"]),
  GUILD_CHANNELS_TOO_LARGE: new ApiException("The channels for this guild are too large", 30061),
  UNAUTHORIZED: new ApiException("Unauthorized. Provide a valid token and try again", 40001),
  ACCOUNT_VERIFICATION_REQUIRED: new ApiException("You need to verify your account in order to perform this action", 40002),
  OPENING_DIRECT_MESSAGES_TOO_FAST: new ApiException("You are opening direct messages too fast", 40003),
  SEND_MESSAGES_DISABLED: new ApiException("Send messages has been temporarily disabled", 40004),
  REQUEST_ENTITY_TOO_LARGE: new ApiException("Request entity too large. Try sending something smaller in size", 40005),
  FEATURE_TEMPORARILY_DISABLED: new ApiException("This feature has been temporarily disabled server-side", 40006),
  USER_BANNED: new ApiException("The user is banned from this guild", 40007),
  CONNECTION_REVOKED: new ApiException("Connection has been revoked", 40012),
  TARGET_USER_IS_NOT_CONNECTED_TO_VOICE: new ApiException("Target user is not connected to voice", 40032),
  ALREADY_CROSSPOSTED: new ApiException("This message has already been crossposted", 40033),
  APPLICATION_COMMAND_ALREADY_EXISTS: new ApiException("An application command with that name already exists", 40041),
  APPLICATION_INTERACTION_SEND_FAILED: new ApiException("Application interaction failed to send", 40043),
  CANNOT_SEND_MESSAGE_FORUM_CHANNEL: new ApiException("Cannot send a message in a forum channel", 40058),
  INTERACTION_ALREADY_ACKED: new ApiException("Interaction has already been acknowledged", 40060),
  TAG_NAMES_UNIQUE: new ApiException("Tag names must be unique", 40061),
  RESOURCE_RATELIMITED: new ApiException("Service resource is being rate limited", 40062),
  NO_TAGS_NON_MODERATOR: new ApiException("There are no tags available that can be set by non-moderators", 40066),
  FORUM_POST_TAG_REQUIRED: new ApiException("A tag is required to create a forum post in this channel", 40067),
  RESOURCE_ENTITLEMENT_ALREADY_GRANTED: new ApiException("An entitlement has already been granted for this resource", 40074),
  CLOUDFLARE_REQUEST_BLOCKED: new ApiException("Cloudflare is blocking your request. This can often be resolved by setting a proper User Agent", 40333),
  MISSING_ACCESS: new ApiException("Missing access", 50001),
  INVALID_ACCOUNT_TYPE: new ApiException("Invalid account type", 50002),
  CANNOT_EXECUTE_ON_DM: new ApiException("Cannot execute action on a DM channel", 50003),
  EMBED_DISABLED: new ApiException("Guild widget disabled", 50004),
  CANNOT_EDIT_MESSAGE_BY_OTHER: new ApiException("Cannot edit a message authored by another user", 50005),
  CANNOT_SEND_EMPTY_MESSAGE: new ApiException("Cannot send an empty message", 50006),
  CANNOT_MESSAGE_USER: new ApiException("Cannot send messages to this user", 50007),
  CANNOT_SEND_MESSAGES_IN_VOICE_CHANNEL: new ApiException("Cannot send messages in a non-text channel", 50008),
  CHANNEL_VERIFICATION_LEVEL_TOO_HIGH: new ApiException("Channel verification level is too high for you to gain access", 50009),
  OAUTH2_APPLICATION_BOT_ABSENT: new ApiException("OAuth2 application does not have a bot", 50010),
  MAXIMUM_OAUTH2_APPLICATIONS: new ApiException("OAuth2 application limit reached", 50011),
  INVALID_OAUTH_STATE: new ApiException("Invalid OAuth2 state", 50012),
  MISSING_PERMISSIONS: new ApiException("You lack permissions to perform that action", 50013),
  INVALID_AUTHENTICATION_TOKEN: new ApiException("Invalid authentication token provided", 50014),
  NOTE_TOO_LONG: new ApiException("Note was too long", 50015),
  INVALID_BULK_DELETE_QUANTITY: new ApiException("Provided too few or too many messages to delete. Must provide at least 2 and fewer than 100 messages to delete", 50016),
  MFA_LEVEL_INVALID: new ApiException("Invalid MFA Level", 50017),
  CANNOT_PIN_MESSAGE_IN_OTHER_CHANNEL: new ApiException("A message can only be pinned to the channel it was sent in", 50019),
  INVALID_OR_TAKEN_INVITE_CODE: new ApiException("Invite code was either invalid or taken", 50020),
  CANNOT_EXECUTE_ON_SYSTEM_MESSAGE: new ApiException("Cannot execute action on a system message", 50021),
  CANNOT_EXECUTE_ON_THIS_CHANNEL_TYPE: new ApiException("Cannot execute action on this channel type", 50024),
  INVALID_OAUTH_TOKEN: new ApiException("Invalid OAuth2 access token provided", 50025),
  MISSING_REQUIRED_OAUTH2_SCOPE: new ApiException("Missing required OAuth2 scope", 50026),
  INVALID_WEBHOOK_TOKEN_PROVIDED: new ApiException("Invalid webhook token provided", 50027),
  INVALID_ROLE: new ApiException("Invalid role", 50028),
  INVALID_RECIPIENT: new ApiException("Invalid Recipient(s)", 50033),
  BULK_DELETE_MESSAGE_TOO_OLD: new ApiException("A message provided was too old to bulk delete", 50034),
  INVALID_FORM_BODY: new ApiException("Invalid form body (returned for both application/json and multipart/form-data bodies), or invalid Content-Type provided", 50035),
  INVITE_ACCEPTED_TO_GUILD_NOT_CONTAINING_BOT: new ApiException("An invite was accepted to a guild the application's bot is not in", 50036),
  INVALID_ACTIVITY_ACTION: new ApiException("Invalid Activity Action", 50039),
  INVALID_API_VERSION: new ApiException("Invalid API version provided", 50041),
  FILE_EXCEEDS_MAXIMUM_SIZE: new ApiException("File uploaded exceeds the maximum size", 50045),
  INVALID_FILE_UPLOADED: new ApiException("Invalid file uploaded", 50046),
  CANNOT_SELF_REDEEM_GIFT: new ApiException("Cannot self-redeem this gift", 50054),
  INVALID_GUILD: new ApiException("Invalid Guild", 50055),
  INVALID_SKU: new ApiException("Invalid SKU", 50057),
  INVALID_REQUEST_ORIGIN: new ApiException("Invalid request origin", 50067),
  INVALID_MESSAGE_TYPE: new ApiException("Invalid message type", 50068),
  PAYMENT_SOURCE_REQUIRED: new ApiException("Payment source required to redeem gift", 50070),
  CANNOT_MODIFY_SYSTEM_WEBHOOK: new ApiException("Cannot modify a system webhook", 50073),
  CANNOT_DELETE_COMMUNITY_REQUIRED_CHANNEL: new ApiException("Cannot delete a channel required for Community guilds", 50074),
  CANNOT_EDIT_STICKERS_IN_MESSAGE: new ApiException("Cannot edit stickers within a message", 50080),
  INVALID_STICKER_SENT: new ApiException("Invalid sticker sent", 50081),
  CANNOT_EDIT_ARCHIVED_THREAD: new ApiException("Tried to perform an operation on an archived thread, such as editing a message or adding a user to the thread", 50083),
  INVALID_THREAD_NOTIFICATION_SETTINGS: new ApiException("Invalid thread notification settings", 50084),
  BEFORE_EARLIER_THAN_THREAD_CREATION_DATE: new ApiException("before value is earlier than the thread creation date", 50085),
  COMMUNITY_SERVER_CHANNELS_TYPE_INVALID: new ApiException("Community server channels must be text channels", 50086),
  EVENT_ENTITY_TYPE_MISMATCH: new ApiException("The entity type of the event is different from the entity you are trying to start the event for", 50091),
  SERVER_NOT_AVAILABLE_IN_YOUR_LOCATION: new ApiException("This server is not available in your location", 50095),
  SERVER_NEEDS_MONETIZATION_ENABLED: new ApiException("This server needs monetization enabled in order to perform this action", 50097),
  MORE_BOOSTS_REQUIRED: new ApiException("This server needs more boosts to perform this action", 50101),
  INVALID_JSON: new ApiException("The request body contains invalid JSON.", 50109),
  OWNER_CANNOT_BE_PENDING_MEMBER: new ApiException("Owner cannot be pending member", 50131),
  OWNERSHIP_TRANSFER_NOT_BOT_USER: new ApiException("Ownership cannot be transferred to a bot user", 50132),
  ASSET_RESIZE_FAILED_BELOW_MAX: new ApiException("Failed to resize asset below the maximum size: 262144", 50138),
  CANNOT_MIX_ROLES_FOR_EMOJI: new ApiException("Cannot mix subscription and non subscription roles for an emoji", 50144),
  CANNOT_CONVERT_BETWEEN_EMOJIS: new ApiException("Cannot convert between premium emoji and normal emoji", 50145),
  UPLOADED_FILE_NOT_FOUND: new ApiException("Uploaded file not found.", 50146),
  VOICE_MESSAGES_ADDITIONAL_CONTEXT_UNSUPPORTED: new ApiException("Voice messages do not support additional content.", 50159),
  VOICE_MESSAGES_SINGLE_AUDIO_ATTACHMENT: new ApiException("Voice messages must have a single audio attachment.", 50160),
  VOICE_MESSAGES_METADATA: new ApiException("Voice messages must have supporting metadata.", 50161),
  VOICE_MESSAGES_CANNOT_EDIT: new ApiException("Voice messages cannot be edited.", 50162),
  GUILD_SUBSCRIPTION_INTEGRATION_CANNOT_DELETE: new ApiException("Cannot delete guild subscription integration", 50163),
  VOICE_MESSAGES_CHANNEL_CANNOT_SEND: new ApiException("You cannot send voice messages in this channel.", 50173),
  USER_ACCOUNT_VERIFICATION_REQUIRED: new ApiException("The user account must first be verified", 50178),
  STICKER_SEND_NO_PERMISSION: new ApiException("You do not have permission to send this sticker.", 50600),
  TWO_FACTOR_REQUIRED: new ApiException("Two factor is required for this operation", 60003),
  NO_USERS_WITH_TAG: new ApiException("No users with Tag exist", 80004),
  REACTION_BLOCKED: new ApiException("Reaction was blocked", 90001),
  USER_NO_BURST_REACTIONS: new ApiException("User cannot use burst reactions", 90002),
  APPLICATION_NOT_AVAILABLE: new ApiException("Application not yet available. Try again later", 110001),
  RESOURCE_OVERLOADED: new ApiException("API resource is currently overloaded. Try again a little later", 130000),
  STAGE_ALREADY_OPEN: new ApiException("The Stage is already open", 150006),
  CANNOT_REPLY_WITHOUT_HISTORY_PERMISSION: new ApiException("Cannot reply without permission to read message history", 160002),
  THREAD_ALREADY_CREATED: new ApiException("A thread has already been created for this message", 160004),
  THREAD_LOCKED: new ApiException("Thread is locked", 160005),
  MAXIMUM_ACTIVE_THREADS_REACHED: new ApiException("Maximum number of active threads reached", 160006),
  MAXIMUM_ACTIVE_ANNOUNCEMENT_THREADS_REACHED: new ApiException("Maximum number of active announcement threads reached", 160007),
  INVALID_JSON_FOR_UPLOADED_LOTTIE_FILE: new ApiException("Invalid JSON for uploaded Lottie file", 170001),
  LOTTIES_CANNOT_CONTAIN_RASTERIZED_IMAGES: new ApiException("Uploaded Lotties cannot contain rasterized images such as PNG or JPEG", 170002),
  STICKER_MAXIMUM_FRAMERATE_REACHED: new ApiException("Sticker maximum framerate exceeded", 170003),
  STICKER_MAXIMUM_FRAME_COUNT_REACHED: new ApiException("Sticker frame count exceeds maximum of 1000 frames", 170004),
  LOTTIE_ANIMATION_MAXIMUM_DIMENSIONS: new ApiException("Lottie animation maximum dimensions exceeded", 170005),
  STICKER_FRAME_RATE_TOO_SMALL_OR_TOO_LARGE: new ApiException("Sticker frame rate is either too small or too large", 170006),
  STICKER_ANIMATION_DURATION_MAXIMUM_REACHED: new ApiException("Sticker animation duration exceeds maximum of 5 seconds", 170007),
  CANNOT_UPDATE_FINISHED_EVENT: new ApiException("Cannot update a finished event", 180000),
  EVENT_STAGE_CREATION_FAILED: new ApiException("Failed to create stage needed for stage event", 180002),
  AUTOMOD_MESSAGE_BLOCKED: new ApiException("Message was blocked by automatic moderation", 200000),
  AUTOMOD_TITLE_BLOCKED: new ApiException("Title was blocked by automatic moderation", 200001),
  WEBHOOK_FORUM_CHANNEL_THREAD_NAME_OR_ID: new ApiException("Webhooks posted to forum channels must have a thread_name or thread_id", 220001),
  WEBHOOK_FORUM_CHANNEL_THREAD_NAME_AND_ID: new ApiException("Webhooks posted to forum channels cannot have both a thread_name and thread_id", 220002),
  WEBHOOK_CREATE_THREADS_IN_FORUM_CHANNELS_ONLY: new ApiException("Webhooks can only create threads in forum channels", 220003),
  WEBHOOK_CANNOT_USE_IN_FORUM_CHANNEL: new ApiException("Webhook services cannot be used in forum channels", 220004),
  MESSAGE_BLOCKED_HARMFUL_LINKS_FILTER: new ApiException("Message blocked by harmful links filter", 240000),
  ONBOARDING_ENABLE_REQUIREMENTS_NOT_MET: new ApiException("Cannot enable onboarding, requirements are not met", 350000),
  ONBOARDING_UPDATE_REQUIRES_NOT_MET: new ApiException("Cannot update onboarding while below requirements", 350001),
  BULK_BAN_FAILED: new ApiException("Failed to ban users", 500000),
  POLL_VOTING_BLOCKED: new ApiException("Poll voting blocked", 520000),
  POLL_EXPIRED: new ApiException("Poll expired", 520001),
  POLL_CREATION_INVALID_CHANNEL_TYPE: new ApiException("Invalid channel type for poll creation", 520002),
  POLL_CANNOT_EDIT: new ApiException("Cannot edit a poll message", 520003),
  POLL_CANNOT_USE_EMOJI: new ApiException("Cannot use an emoji included with the poll", 520004),
  CANNOT_EXPIRE_NON_POLL_MESSAGE: new ApiException("Cannot expire a non-poll message", 520006),
};

export enum FieldErrorTypes {
  BASE_TYPE_REQUIRED = "BASE_TYPE_REQUIRED",
  BASE_TYPE_STRING = "BASE_TYPE_STRING",
  BASE_TYPE_NUMBER = "BASE_TYPE_NUMBER",
  BASE_TYPE_BIGINT = "BASE_TYPE_BIGINT",
  BASE_TYPE_BOOLEAN = "BASE_TYPE_BOOLEAN",
  BASE_TYPE_CHOICES = "BASE_TYPE_CHOICES",
  BASE_TYPE_CLASS = "BASE_TYPE_CLASS",
  BASE_TYPE_OBJECT = "BASE_TYPE_OBJECT",
  BASE_TYPE_ARRAY = "BASE_TYPE_ARRAY",
  UNKOWN_FIELD = "UNKOWN_FIELD",
  BASE_TYPE_CONSTANT = "BASE_TYPE_CONSTANT",
  EMAIL_TYPE_INVALID_EMAIL = "EMAIL_TYPE_INVALID_EMAIL",
  DATE_TYPE_PARSE = "DATE_TYPE_PARSE",
  BASE_TYPE_BAD_LENGTH = "BASE_TYPE_BAD_LENGTH",
  BASE_TYPE_INVALID = "BASE_TYPE_INVALID",
}

export const FieldErrorMessages = {
  BASE_TYPE_REQUIRED: "This field is required",
  BASE_TYPE_STRING: "This field must be a string",
  BASE_TYPE_NUMBER: "This field must be a number",
  BASE_TYPE_BIGINT: "This field must be a bigint",
  BASE_TYPE_BOOLEAN: "This field must be a boolean",
  BASE_TYPE_CHOICES: "This field must be one of ({{types}})",
  BASE_TYPE_CLASS: "This field must be an instance of {{type}}",
  BASE_TYPE_OBJECT: "This field must be an object",
  BASE_TYPE_ARRAY: "This field must be an array",
  UNKOWN_FIELD: "Unknown key: {{key}}",
  BASE_TYPE_CONSTANT: "This field must be {{value}}",
  EMAIL_TYPE_INVALID_EMAIL: "Not a well-formed email address",
  DATE_TYPE_PARSE: "Could not parse {{date}}. Should be ISO8601",
  BASE_TYPE_BAD_LENGTH: "Must be between {{length}} in length",
  BASE_TYPE_INVALID: "Invalid Form Body",
};
